title: rgmagadan
description: Sitio con apuntes de programación, accesibilidad, lectores de pantalla,  y tecnología en general.
remote_theme: pages-themes/minimal@v0.2.0
paginate: 5
plugins:
  - jekyll-paginate
  - jekyll-remote-theme
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "Ramón"