title: rgmagadan
description: Sitio con apuntes de programación, accesibilidad, lectores de pantalla,  y tecnología en general.
remote_theme: pages-themes/minimal@v0.2.0
paginate: 5
plugins:
- jekyll-paginate
- jekyll-remote-theme